[build]
  command = "rm -rf node_modules && npm install --force && ng build --prod" 
  publish = "dist/site.pedyc/browser" # 替换为实际输出路径

[build.environment]
npm_config_platform = "linux"  # 关键！通过 npm 专用环境变量指定平台
NPM_FLAGS = "--force"   
